baseurl = "https://www.bootingup.net/" 
title = "Bootingup.net"
author = "Peeanio"
theme = ["ananke"]
SectionPagesMenu = "main"
renderer.unsafe = true

[[params.ananke_socials]]
name = "github"
url = "https://github.com/Peeanio"

[params.ananke.social.follow]
new_window_icon = false
networks = []
