baseurl = "https://www.bootingup.net/" 
title = "Bootingup.net"
author = "Peeanio"
theme = "ananke"
SectionPagesMenu = "main"
renderer.unsafe = true

theme = ["anake"]

[[params.ananke_socials]]
name = "github"
url = "https://github.com/Peeanio"
